"""empty message

Revision ID: 446c613e17f8
Revises: 
Create Date: 2020-08-04 01:48:41.462361

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '446c613e17f8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('program',
    sa.Column('program_id', sa.Integer(), nullable=False),
    sa.Column('program_name', sa.String(length=64), nullable=True),
    sa.Column('program_description', sa.String(length=140), nullable=True),
    sa.PrimaryKeyConstraint('program_id')
    )
    op.create_index(op.f('ix_program_program_description'), 'program', ['program_description'], unique=False)
    op.create_index(op.f('ix_program_program_name'), 'program', ['program_name'], unique=False)
    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('about_me', sa.String(length=140), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('product',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('product_type', sa.String(length=64), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('product_description', sa.String(length=200), nullable=True),
    sa.Column('image_path', sa.String(length=60), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('product_id')
    )
    op.create_index(op.f('ix_product_product_type'), 'product', ['product_type'], unique=False)
    op.create_index(op.f('ix_product_timestamp'), 'product', ['timestamp'], unique=False)
    op.create_table('stage',
    sa.Column('stage_id', sa.Integer(), nullable=False),
    sa.Column('stage_name', sa.String(), nullable=True),
    sa.Column('start', sa.Integer(), nullable=True),
    sa.Column('end', sa.Integer(), nullable=True),
    sa.Column('program_id', sa.Integer(), nullable=True),
    sa.Column('Event', sa.NullType(), nullable=True),
    sa.ForeignKeyConstraint(['program_id'], ['program.program_id'], ),
    sa.PrimaryKeyConstraint('stage_id')
    )
    op.create_index(op.f('ix_stage_end'), 'stage', ['end'], unique=False)
    op.create_index(op.f('ix_stage_stage_name'), 'stage', ['stage_name'], unique=False)
    op.create_index(op.f('ix_stage_start'), 'stage', ['start'], unique=False)
    op.create_table('user_roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('event',
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('event_description', sa.String(), nullable=True),
    sa.Column('stage_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['stage_id'], ['stage.stage_id'], ),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_index(op.f('ix_event_event_description'), 'event', ['event_description'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_event_event_description'), table_name='event')
    op.drop_table('event')
    op.drop_table('user_roles')
    op.drop_index(op.f('ix_stage_start'), table_name='stage')
    op.drop_index(op.f('ix_stage_stage_name'), table_name='stage')
    op.drop_index(op.f('ix_stage_end'), table_name='stage')
    op.drop_table('stage')
    op.drop_index(op.f('ix_product_timestamp'), table_name='product')
    op.drop_index(op.f('ix_product_product_type'), table_name='product')
    op.drop_table('product')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_table('role')
    op.drop_index(op.f('ix_program_program_name'), table_name='program')
    op.drop_index(op.f('ix_program_program_description'), table_name='program')
    op.drop_table('program')
    # ### end Alembic commands ###
