"""incrementing age in subscription Model

Revision ID: d748ba77888f
Revises: a51d0c3bcbe3
Create Date: 2020-11-28 11:52:38.619830

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd748ba77888f'
down_revision = 'a51d0c3bcbe3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subscription_day', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_subscriptions_subscription_day'), ['subscription_day'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subscriptions_subscription_day'))
        batch_op.drop_column('subscription_day')

    # ### end Alembic commands ###
